### NumPy crash course

In [1]:
import numpy as np

### NumPy arrays

In [2]:
my_list = [1, 2, 3]

In [4]:
type(np.array(my_list))

numpy.ndarray

In [28]:
arr = np.array(my_list)
arr

array([1, 2, 3])

### <b>np.arange: </b> 
Similar to python's range function.

``` Returns evenly spaced values within given interval```


In [12]:
np.arange(0, 11,2)

array([ 0,  2,  4,  6,  8, 10])

### NumPy functions to create specific arrays:


In [16]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [18]:
np.ones((2,8))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

### Create linearly spaced arrays:


In [22]:
np.linspace(0, 11, 100)

array([  0.        ,   0.11111111,   0.22222222,   0.33333333,
         0.44444444,   0.55555556,   0.66666667,   0.77777778,
         0.88888889,   1.        ,   1.11111111,   1.22222222,
         1.33333333,   1.44444444,   1.55555556,   1.66666667,
         1.77777778,   1.88888889,   2.        ,   2.11111111,
         2.22222222,   2.33333333,   2.44444444,   2.55555556,
         2.66666667,   2.77777778,   2.88888889,   3.        ,
         3.11111111,   3.22222222,   3.33333333,   3.44444444,
         3.55555556,   3.66666667,   3.77777778,   3.88888889,
         4.        ,   4.11111111,   4.22222222,   4.33333333,
         4.44444444,   4.55555556,   4.66666667,   4.77777778,
         4.88888889,   5.        ,   5.11111111,   5.22222222,
         5.33333333,   5.44444444,   5.55555556,   5.66666667,
         5.77777778,   5.88888889,   6.        ,   6.11111111,
         6.22222222,   6.33333333,   6.44444444,   6.55555556,
         6.66666667,   6.77777778,   6.88888889,   7.  

### Random NumPy arrays:
Return random integers from `low` (inclusive) to `high` (exclusive).


In [49]:
np.random.randint(0, 10)

4

In [30]:
np.random.randint(0, 1000, (3,3))

array([[586, 275, 291],
       [887, 565, 579],
       [  5, 731, 253]])

In [41]:
np.random.seed(42)
np.random.randint(0, 1000, 10)

array([102, 435, 860, 270, 106,  71, 700,  20, 614, 121])

In [44]:
np.random.randint(0, 1000, 10)

array([466, 214, 330, 458,  87, 372,  99, 871, 663, 130])

### Other useful operations:



In [47]:
np.random.seed(101)
arr = np.random.randint(0, 1000, 10)

In [50]:
arr

array([863, 523, 337, 838, 575, 599,  75, 393, 973, 552])

In [51]:
arr.max()

973

In [52]:
arr.min()

75

In [53]:
arr.mean()

572.79999999999995

In [60]:
'''returns the index location of the max value'''
arr.argmax()

8

In [61]:
'''returns the index location of the min value'''
arr.argmin()

6

In [62]:
arr

array([863, 523, 337, 838, 575, 599,  75, 393, 973, 552])

```
a.reshape(shape, order='C')

Returns an array containing the same data with a new shape.```

In [63]:
arr.reshape(2,5)

array([[863, 523, 337, 838, 575],
       [599,  75, 393, 973, 552]])

```Indexes:```

In [77]:
mat = np.linspace(0, 100, 25).reshape(5, 5)
mat

array([[   0.        ,    4.16666667,    8.33333333,   12.5       ,
          16.66666667],
       [  20.83333333,   25.        ,   29.16666667,   33.33333333,   37.5       ],
       [  41.66666667,   45.83333333,   50.        ,   54.16666667,
          58.33333333],
       [  62.5       ,   66.66666667,   70.83333333,   75.        ,
          79.16666667],
       [  83.33333333,   87.5       ,   91.66666667,   95.83333333,  100.        ]])

In [78]:
mat = np.arange(0, 100).reshape(10, 10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [109]:
assert mat[3,3] == 33
mat[3, 3]

mat[:,0].reshape(10, 1)

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [90]])

In [110]:
mat[7,:]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

```Slicing:```

In [114]:
mat[0:4, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

```Masking:```

In [116]:
mat > 30

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

In [117]:
filter = mat > 30
mat[filter]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
       99])

```Boolean masking:```

In [120]:
mat[mat>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
       99])