# TF syntax basics

In [16]:
import tensorflow as tf

In [17]:
print(tf.__version__)

1.3.0


In [18]:
hello = tf.constant("Hello")

In [19]:
world = tf.constant("world")

In [20]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [21]:
print(hello)

Tensor("Const_4:0", shape=(), dtype=string)


In [22]:
with tf.Session() as sess:
    result = sess.run(hello + ' ' +  world)

In [23]:
print(result)

b'Hello world'


In [24]:
a = tf.constant(10)

In [25]:
b = tf.constant(32)

In [26]:
type(a)

tensorflow.python.framework.ops.Tensor

In [27]:
a + b 

<tf.Tensor 'add_7:0' shape=() dtype=int32>

In [28]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [29]:
result

42

In [30]:
const = tf.constant(10)

In [31]:
const

<tf.Tensor 'Const_8:0' shape=() dtype=int32>

In [32]:
fill_mat = tf.fill((4,4), 22)

In [33]:
fill_mat

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [35]:
zeros = tf.zeros((4,4))

In [36]:
ones = tf.ones((4,4))

In [43]:
rand_normal = tf.random_normal((4,4), mean=10, stddev=1.5)

In [44]:
rand_uniform = tf.random_uniform((4,4), minval=2, maxval=10)

In [45]:
operations = [const, fill_mat, zeros, ones, rand_normal, rand_uniform]

In [47]:
# interactive setting: useful only for a notebook setting
sess = tf.InteractiveSession()

In [49]:
for op in operations:
    print('\n', sess.run(op))
    print('\n', op.eval())


 10

 10

 [[22 22 22 22]
 [22 22 22 22]
 [22 22 22 22]
 [22 22 22 22]]

 [[22 22 22 22]
 [22 22 22 22]
 [22 22 22 22]
 [22 22 22 22]]

 [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

 [[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]

 [[  9.98975849  10.5661726   11.4235611    6.99471188]
 [ 11.79609108   5.94628716  12.0737114   11.170784  ]
 [  9.05959797  10.59453106  11.50850105   8.82901859]
 [  8.20671749   9.88101864  10.07228756  11.30330372]]

 [[  9.74657536  11.64115238   9.13844585   9.71251202]
 [  9.70821095  13.31922436  11.83899021  10.07872391]
 [  9.41908455   6.64421082  13.87330246   9.51253605]
 [  9.337883     9.26916695   7.31406784  13.56914139]]

 [[ 8.7934351   9.66638184  2.98947144  8.34853172]
 [ 3.3837595   8.92870426  9.51831532  4.99289227

In [50]:
a = tf.constant([[1, 2],
                [3, 4]])

In [51]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [56]:
a.eval()

array([[1, 2],
       [3, 4]], dtype=int32)

In [52]:
b = tf.constant([[10], [100]])

In [53]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [54]:
result = tf.matmul(a, b)

In [55]:
sess.run(result)

array([[210],
       [430]], dtype=int32)